steps:
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=${_BACKEND_IMAGE}:${SHORT_SHA}
      - --tag=${_BACKEND_IMAGE}:latest
      - backend

  - id: push-backend-short-sha
    name: gcr.io/cloud-builders/docker
    args: ["push", "${_BACKEND_IMAGE}:${SHORT_SHA}"]

  - id: push-backend-latest
    name: gcr.io/cloud-builders/docker
    args: ["push", "${_BACKEND_IMAGE}:latest"]

  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=frontend/Dockerfile
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - --tag=${_FRONTEND_IMAGE}:${SHORT_SHA}
      - --tag=${_FRONTEND_IMAGE}:latest
      - frontend

  - id: push-frontend-short-sha
    name: gcr.io/cloud-builders/docker
    args: ["push", "${_FRONTEND_IMAGE}:${SHORT_SHA}"]

  - id: push-frontend-latest
    name: gcr.io/cloud-builders/docker
    args: ["push", "${_FRONTEND_IMAGE}:latest"]

substitutions:
  _AR_REPO: europe-southwest1-docker.pkg.dev/onboarding-dev-487716/repo-onboarding-dev
  _BACKEND_IMAGE: ${_AR_REPO}/backend
  _FRONTEND_IMAGE: ${_AR_REPO}/frontend
  _VITE_API_URL: https://backend-onboarding-866351374703.europe-southwest1.run.app/api

images:
  - ${_BACKEND_IMAGE}:${SHORT_SHA}
  - ${_BACKEND_IMAGE}:latest
  - ${_FRONTEND_IMAGE}:${SHORT_SHA}
  - ${_FRONTEND_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
